# Generated by Django 2.1.4 on 2019-02-13 12:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('topic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sort_model',
            name='manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='板块管理人'),
        ),
        migrations.AddField(
            model_name='sort_model',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='childcolumn', to='topic.Sort_Model'),
        ),
        migrations.AddField(
            model_name='create_topic_model',
            name='node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='topic.Sort_Model', verbose_name='文章分类'),
        ),
        migrations.AddField(
            model_name='create_topic_model',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='作者'),
        ),
        migrations.AddField(
            model_name='carousel_model',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='topic.Create_Topic_Model', verbose_name='关联文章'),
        ),
        migrations.AddField(
            model_name='agreemodel',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='topic.Create_Topic_Model', verbose_name='被点赞的文章'),
        ),
        migrations.AddField(
            model_name='agreemodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='点赞用户'),
        ),
    ]
