# Generated by Django 2.1.4 on 2019-03-06 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0002_auto_20190213_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='create_topic_model',
            name='zhihu_id',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='是否为知乎文章'),
        ),
        migrations.AlterField(
            model_name='create_topic_model',
            name='title',
            field=models.CharField(max_length=200, verbose_name='标题'),
        ),
    ]
